server:
  port: 8086

spring:
  application:
    name: AccessLimitProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?accesslimit=true&characterEncoding=utf8serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    port: 6379
    host: localhost
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s


accesslimit:
  second: 5
  time: 3
  lockTime: 10

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: xndaRCZRw1FAkgbOV52Y
  secretKey: k69XaEw6Su43pDKrzcyQMdU7ZorregdCMGMoU0Zq
  bucketName: test
  imageSize: 10485760
  fileSize: 1073741824



